const String = @import("string.zig").String;
const Array = @import("array.zig").Array;

pub const ValueTag = enum(c_int) {
    None = 0,
    Bool = 1,
    Int = 2,
    Float = 3,
    String = 4,
    Array = 5,
    Set = 6,
    Map = 7,
    Option = 8,
    Result = 9,
    Class = 10,
    OwnedInterface = 11,
    InterfaceRef = 12,
    ConstRef = 13,
    MutRef = 14,
    Unique = 15,
    Shared = 16,
    Weak = 17,
    FunctionPtr = 18,
    Vec2i = 19,
    Vec3i = 20,
    Vec4i = 21,
    Vec2f = 22,
    Vec3f = 23,
    Vec4f = 24,
    Mat3f = 25,
    Mat4f = 26,
};

pub const RawValue = extern union {
    boolean: bool,
    int: i64,
    float: f64,
    string: String,
    array: Array,
    // map: Map,
    // set: Set,
    // option: Option,
    // result: Result,
    // class: Class,
    // ownedInterface: OwnedInterface,
    // interfaceRef: *InterfaceRef,
    // constRef: ValueConstRef,
    // mutRef: ValueMutRef,
    // unique: Unique,
    // shared: Shared,
    // weak: Weak,
    // functionPtr: FunctionPtr,
    // vec2i: Vec2i,
    // vec3i: Vec3i,
    // vec4i: Vec4i,
    // vec2f: Vec2f,
    // vec3f: Vec3f,
    // vec4f: Vec4f,
    // mat3f: Mat3f,
    // mat4f: Mat4f,
};

/// Compatible with C
pub const TaggedValue = extern struct {
    tag: ValueTag,
    value: RawValue,
};
